import os
import streamlit as st
import pandas as pd


# Global Page Configuration
st.set_page_config(
    page_title="HRL Crypto Trading Bot",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded"
)

@st.cache_data(ttl=10)  # reload CSV data every 10 seconds
def load_real_data():
    # Read log file generated by simu_trade.py
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    log_path = os.path.join(BASE_DIR, "trading", "dry_run_log.csv")
    
    # Return empty if file doesn't exist or is empty
    if not os.path.exists(log_path) or os.path.getsize(log_path) == 0:
        return pd.DataFrame(), {}, {}, pd.DataFrame()

    try:
        df = pd.read_csv(log_path)
        if len(df) == 0:
            return pd.DataFrame(), {}, {}, pd.DataFrame()
            
        # Data type conversion and cleaning
        df['Datetime'] = pd.to_datetime(df['Timestamp (UTC)'], format='%H:%M:%S', errors='coerce')
        df['Portfolio_Value'] = df['Total_Portfolio_Value'].astype(float)
        df['BTC_Price'] = df['BTC_Price'].astype(float)
        
        # Extract the latest step's weight status
        latest_row = df.iloc[-1]
        
        target_weights = {
            'USDT': float(latest_row['Target_Cash_Pct']), 
            'BTC': float(latest_row['Target_BTC_Pct'])
        }
        
        actual_weights = {
            'USDT': float(latest_row['Actual_Cash_Pct']), 
            'BTC': float(latest_row['Actual_BTC_Pct'])
        }
        
        # Extract trade logs
        trade_logs = df[df['Trade_Action'] != 'Hold'].tail(10)[
            ['Timestamp (UTC)', 'Trade_Action', 'BTC_Price', 'Total_Portfolio_Value']
        ]
        
        return df, target_weights, actual_weights, trade_logs

    except Exception as e:
        st.error(f"Failed to load logs: {e}")
        return pd.DataFrame(), {}, {}, pd.DataFrame()

# Sidebar
with st.sidebar:
    st.title("⚙️ Control Panel")
    st.markdown("### Model Configuration")
    
    selected_model = st.selectbox(
        "Select Model (Ablation)",
        ("HIRO HRL (Ours)", "Risk-aware SAC", "Baseline SAC")
    )
    
    selected_asset = st.selectbox("Trading Asset", ("BTC/USDT", "ETH/USDT"))
    
    st.markdown("---")
    st.info("Hierarchical Reinforcement Learning for Mid-Frequency Crypto Trading.")

# Dashboard
st.title("📈 HRL Dry Run Dashboard")
st.markdown(f"**Current Model:** `{selected_model}` | **Asset:** `{selected_asset}`")

# Fetch data
df_history, target_w, actual_w, trade_logs = load_real_data()

if df_history.empty:
    st.warning("⏳ Waiting for simu_trade.py to generate data... Please run the trading script first.")
    st.stop() # Stop rendering components below

# Core KPI Cards
st.markdown("### 📊 Performance Indicators")
col1, col2, col3, col4 = st.columns(4)